DROP DATABASE IF EXISTS test1;
DROP DATABASE IF EXISTS test2;

DROP USER IF EXISTS alice;
CREATE USER alice WITH PASSWORD 'wonderland';
DROP USER IF EXISTS bob;
CREATE USER bob WITH PASSWORD 'ross';

CREATE DATABASE test1 WITH OWNER alice;
CREATE DATABASE test2 WITH OWNER bob;
